services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    shm_size: 128mb
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '12345'
      POSTGRES_USER: 'tech'
      POSTGRES_DB: 'shop'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
