# Generated by Django 5.2.1 on 2025-07-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_created_at_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
    ]
