# Generated by Django 5.2.1 on 2025-06-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
